import { useState, useEffect } from 'react';
import styled, { css, keyframes } from 'styled-components';
import Head from 'next/head';
import Image from 'next/image';

import igorPic from '../assets/me.jpg';
import cardAge from '../assets/CardAge.svg';
import cardLocation from '../assets/CardLocation.svg';
import cardMobileDev from '../assets/CardMobileDev.svg';
import cardWebDev from '../assets/CardWebDev.svg';
import cardDesigner from '../assets/CardDesigner.svg';
import cardSkills from '../assets/CardSkills.svg';
import cardLanguages from '../assets/CardLanguages.svg';
import Navigation from '../components/Navigation';
import PageLayout from '../components/PageLayout';
import Card from '../components/Card';
import useIsPageClosing from '../hooks/useIsPageClosing';
import { DEFAULT_TRANSITION_DURATION } from '../constants/variables';

const About = () => {
  const isPageClosing = useIsPageClosing();

  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section goAway={isPageClosing}>
        <IgorPicWrapper>
          <Image src={igorPic} height="350" width="350" alt="Igor Marcossi picture" />
        </IgorPicWrapper>
        <div>
          <Title>
            I&apos;m Igor,
            <br />
            pleasure to meet ya 👋
          </Title>
          <BigText>
            I&apos;m a fullstack JS Developer for 8+ years of experience and a graphic/UI designer for 14+ years of
            experience.
          </BigText>
          <PhotoWrapper>
            <Image src={cardAge} height="110" width="110" alt="Igor Marcossi picture" />
            <Image src={cardLocation} height="110" width="110" alt="Igor Marcossi picture" />
            <Image src={cardMobileDev} height="110" width="110" alt="Igor Marcossi picture" />
            <Image src={cardWebDev} height="110" width="110" alt="Igor Marcossi picture" />
            <Image src={cardDesigner} height="110" width="110" alt="Igor Marcossi picture" />
          </PhotoWrapper>
        </div>
      </Section>
      <Section goAway={isPageClosing}>
        <div>
          <TitlePurple>What happened</TitlePurple>
          <Text>
            I’ve been working with computers throughout all my life. I love technology and I have a deep passion for
            logic and solving problems. Creating solutions that make the world more beautiful and more functional is
            what makes me keep moving. I keep some open source projects on GitHub and contributed to some other ones.
            I’ve been creating, designing and developing projects for so many years that it became my way of thinking. I
            always want to find better solutions to what we have.
          </Text>
        </div>
        <CardsWrapper>
          <Image src={cardSkills} height="149" width="233" alt="Igor Marcossi picture" />
          <Image src={cardLanguages} height="114" width="216" alt="Igor Marcossi picture" />
        </CardsWrapper>
      </Section>
    </>
  );
};

About.getLayout = (page) => <PageLayout>{page}</PageLayout>;

export default About;

const fadeIn = keyframes`
  0% {
    opacity: 0;
  }
  100% {
    transform: 1;
  }
`;

const Section = styled.div`
  display: flex;
  /* flex-wrap: wrap;s */
  align-items: center;
  transition: opacity ${DEFAULT_TRANSITION_DURATION}ms;
  opacity: ${({ goAway }) => (!goAway ? 1 : 0)};
  animation: ${fadeIn} ${DEFAULT_TRANSITION_DURATION}ms ease-out;
  margin: 64px 0;
  gap: 32px;
`;

const IgorPicWrapper = styled.div`
  border-radius: 80px;
  overflow: hidden;
  display: inline-block;
  font-size: 0;
`;

const PhotoWrapper = styled.div`
  display: flex;
  align-items: center;
  gap: 8px;
  margin-top: 8px;
`;

const CardsWrapper = styled.div`
  position: relative;
  flex-basis: 40%;
  flex-shrink: 0;
  height: 110%;
  & > div:first-child {
    position: absolute !important;
    top: 8px;
    right: 0;
  }
  & > div:last-child {
    position: absolute !important;
    bottom: 8px;
    left: 0;
  }
`;

const Title = styled.p`
  font-size: 32px;
  font-weight: 700;
  margin: 0;
  margin-bottom: 8px;
`;

const TitlePurple = styled.p`
  font-size: 32px;
  font-weight: 700;
  margin: 0;
  margin-bottom: 8px;
  color: #a247cc;
`;

const BigText = styled.p`
  font-size: 24px;
  margin: 0;
`;

const Text = styled.p`
  font-size: 18px;
  margin: 8px 0;
`;
