import styled from 'styled-components';
import Head from 'next/head';

import PageLayout from '../components/PageLayout';
import Navigation from '../components/Navigation';
import useIsPageClosing from '../hooks/useIsPageClosing';

export default function Contact() {
  const isPageClosing = useIsPageClosing();
  return (
    <>
      <Head>
        <title>Igor Marcossi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        Contact
      </Head>
    </>
  );
}

Contact.getLayout = (page) => <PageLayout>{page}</PageLayout>;
