import styled from 'styled-components';
import Head from 'next/head';

import PageLayout from '../components/PageLayout';
import useIsPageClosing from '../hooks/useIsPageClosing';

const MyWorks = () => {
  const isPageClosing = useIsPageClosing();
  return (
    <>
      <Head>
        <title>Igor Marcossi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        My works
      </Head>
    </>
  );
};

MyWorks.getLayout = (page) => <PageLayout>{page}</PageLayout>;

export default MyWorks;
